web_scripts:
  build: docker_build/drupal8/development
  volumes:
   - ./public_html:/var/www/html
   - ./dev-scripts/:/root/dev-scripts
   - ./test-results/:/root/test-results

web:
  image: goalgorilla/drupal_social
  volumes:
   - ./public_html:/var/www/html
  links:
   - db:db


db_data:
  image: mysql:5.6
  environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=social
  container_name: db_data
  command: /bin/true
  volumes:
    - /var/lib/mysql

db:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=social
  volumes_from:
    - db_data
  ports:
    - "3307:3306"